<a href="https://colab.research.google.com/github/srivatsan88/YouTubeLI/blob/master/K_Prototype_for_Mixed_Datatypes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install kmodes

In [0]:
import numpy as np
import pandas as pd

from kmodes.kprototypes import KPrototypes

In [0]:
marketing_df = pd.read_csv('https://raw.githubusercontent.com/srivatsan88/YouTubeLI/master/dataset/marketing_cva_f.csv')

In [3]:
marketing_df

     Customer       State  ...  Vehicle_Class avg_vehicle_age
0     BU79786  Washington  ...   Two-Door Car       40.696695
1     AI49188      Nevada  ...   Two-Door Car       48.755298
2     HB64268  Washington  ...  Four-Door Car       70.394474
3     OC83172      Oregon  ...   Two-Door Car       53.460212
4     XZ87318      Oregon  ...  Four-Door Car       32.811507
...       ...         ...  ...            ...             ...
6812  TF56202  California  ...   Two-Door Car       37.492591
6813  YM19146  California  ...  Four-Door Car       48.946675
6814  LA72316  California  ...  Four-Door Car       65.310053
6815  PK87824  California  ...  Four-Door Car       48.002914
6816  UP19263  California  ...  Four-Door Car       45.151858

[6817 rows x 12 columns]

In [0]:
marketing_df=marketing_df.drop(['Customer','Vehicle_Class','avg_vehicle_age','months_last_claim','Total_Claim_Amount'],axis=1)

In [5]:
marketing_df

           State           CLV  ... monthly_premium  Months_Since_Policy_Inception
0     Washington   2763.519279  ...              69                              5
1         Nevada  12887.431650  ...             108                             38
2     Washington   2813.692575  ...              73                             44
3         Oregon   8256.297800  ...              69                             94
4         Oregon   5380.898636  ...              67                             13
...          ...           ...  ...             ...                            ...
6812  California   5032.165498  ...              64                             48
6813  California   4100.398533  ...             104                             58
6814  California  23405.987980  ...              73                             89
6815  California   3096.511217  ...              79                             28
6816  California   7524.442436  ...              96                              3

[6817 rows x 7 columns]

In [0]:
mark_array=marketing_df.values

In [0]:
mark_array[:, 1] = mark_array[:, 1].astype(float)
mark_array[:, 3] = mark_array[:, 1].astype(float)
mark_array[:, 5] = mark_array[:, 1].astype(float)
mark_array[:, 6] = mark_array[:, 1].astype(float)

In [8]:
mark_array

array([['Washington', 2763.519279, 'Basic', ..., 'Suburban', 2763.519279,
        2763.519279],
       ['Nevada', 12887.43165, 'Premium', ..., 'Suburban', 12887.43165,
        12887.43165],
       ['Washington', 2813.692575, 'Basic', ..., 'Rural', 2813.692575,
        2813.692575],
       ...,
       ['California', 23405.98798, 'Basic', ..., 'Urban', 23405.98798,
        23405.98798],
       ['California', 3096.511217, 'Extended', ..., 'Suburban',
        3096.511217, 3096.511217],
       ['California', 7524.442436, 'Extended', ..., 'Suburban',
        7524.442436, 7524.442436]], dtype=object)

In [9]:
kproto = KPrototypes(n_clusters=3, verbose=2,max_iter=20)
clusters = kproto.fit_predict(mark_array, categorical=[0, 2, 4])

Init: initializing centroids
Init: initializing clusters
Init: initializing centroids
Init: initializing clusters
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 1, iteration: 1/20, moves: 867, ncost: 258714011109.16388
Run: 1, iteration: 2/20, moves: 174, ncost: 255289895466.8784
Run: 1, iteration: 3/20, moves: 62, ncost: 254916955870.9604
Run: 1, iteration: 4/20, moves: 49, ncost: 254762284578.1473
Run: 1, iteration: 5/20, moves: 30, ncost: 254675634634.70587
Run: 1, iteration: 6/20, moves: 54, ncost: 254457837198.26227
Run: 1, iteration: 7/20, moves: 39, ncost: 254348949584.06052
Run: 1, iteration: 8/20, moves: 19, ncost: 254318621820.413
Run: 1, iteration: 9/20, moves: 10, ncost: 254287035052.18463
Run: 1, iteration: 10/20, moves: 17, ncost: 254234139353.94614
Run: 1, iteration: 11/20, moves: 9, ncost: 254227872537.46252
Run: 1, iteration: 12/20, moves: 18, ncost: 254193766291.3935
Run: 1, iteration: 13/20, moves: 24, ncost: 254151421297.3616
Run: 1, iteration: 14/20, moves: 15, ncost: 254092569844.63184
Run: 1, iteration: 15/20, moves: 12, ncost: 254028419014.68417
Run: 1, iteration: 16/20, moves: 11, ncost: 254013792315.71866
Run: 1, iteration: 17/20, moves: 5, ncost: 254011889109.24292
Run: 1, iteration: 18/20, moves: 0, ncost: 254011889109.24292
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 2, iteration: 1/20, moves: 1432, ncost: 286155034778.45355
Run: 2, iteration: 2/20, moves: 274, ncost: 261001609809.572
Run: 2, iteration: 3/20, moves: 222, ncost: 257967595036.51343
Run: 2, iteration: 4/20, moves: 150, ncost: 256836544589.50055
Run: 2, iteration: 5/20, moves: 99, ncost: 256466445049.71188
Run: 2, iteration: 6/20, moves: 73, ncost: 256231828172.96753
Run: 2, iteration: 7/20, moves: 40, ncost: 256126129149.77405
Run: 2, iteration: 8/20, moves: 50, ncost: 256037495161.13043
Run: 2, iteration: 9/20, moves: 45, ncost: 255941030693.37964
Run: 2, iteration: 10/20, moves: 40, ncost: 255843783691.12393
Run: 2, iteration: 11/20, moves: 35, ncost: 255792047572.66052
Run: 2, iteration: 12/20, moves: 27, ncost: 255754970004.72733
Run: 2, iteration: 13/20, moves: 34, ncost: 255709814479.9524
Run: 2, iteration: 14/20, moves: 14, ncost: 255701205250.88058
Run: 2, iteration: 15/20, moves: 7, ncost: 255699397602.56784
Run: 2, iteration: 16/20, moves: 2, ncost: 255699223839.03928
Run: 2, iteration: 17/20, moves: 2, ncost: 255699017354.36984
Run: 2, iteration: 18/20, moves: 2, ncost: 255698926481.13284
Run: 2, iteration: 19/20, moves: 3, ncost: 255698716105.73767
Run: 2, iteration: 20/20, moves: 0, ncost: 255698716105.73767
Init: initializing centroids
Init: initializing clusters
Init: initializing centroids
Init: initializing clusters
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 3, iteration: 1/20, moves: 1604, ncost: 348478082338.6739
Run: 3, iteration: 2/20, moves: 1401, ncost: 275390913697.4201
Run: 3, iteration: 3/20, moves: 451, ncost: 260518346922.14093
Run: 3, iteration: 4/20, moves: 227, ncost: 257850462600.96158
Run: 3, iteration: 5/20, moves: 149, ncost: 256819398967.867
Run: 3, iteration: 6/20, moves: 99, ncost: 256453653621.0911
Run: 3, iteration: 7/20, moves: 70, ncost: 256228179953.5385
Run: 3, iteration: 8/20, moves: 39, ncost: 256124460537.68063
Run: 3, iteration: 9/20, moves: 50, ncost: 256036051526.73767
Run: 3, iteration: 10/20, moves: 45, ncost: 255939063769.12854
Run: 3, iteration: 11/20, moves: 39, ncost: 255843783691.12396
Run: 3, iteration: 12/20, moves: 35, ncost: 255792047572.66037
Run: 3, iteration: 13/20, moves: 27, ncost: 255754970004.72766
Run: 3, iteration: 14/20, moves: 34, ncost: 255709814479.95303
Run: 3, iteration: 15/20, moves: 14, ncost: 255701205250.8805
Run: 3, iteration: 16/20, moves: 7, ncost: 255699397602.5678
Run: 3, iteration: 17/20, moves: 2, ncost: 255699223839.03906
Run: 3, iteration: 18/20, moves: 2, ncost: 255699017354.3699
Run: 3, iteration: 19/20, moves: 2, ncost: 255698926481.13293
Run: 3, iteration: 20/20, moves: 3, ncost: 255698716105.73755
Run: 3, iteration: 21/20, moves: 0, ncost: 255698716105.73755
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 4, iteration: 1/20, moves: 1079, ncost: 268368159061.15845
Run: 4, iteration: 2/20, moves: 167, ncost: 259404342173.26624
Run: 4, iteration: 3/20, moves: 163, ncost: 257410262595.2164
Run: 4, iteration: 4/20, moves: 133, ncost: 256673753588.94006
Run: 4, iteration: 5/20, moves: 91, ncost: 256393122345.27036
Run: 4, iteration: 6/20, moves: 49, ncost: 256207776993.60333
Run: 4, iteration: 7/20, moves: 32, ncost: 256122799236.49957
Run: 4, iteration: 8/20, moves: 49, ncost: 256036051526.73755
Run: 4, iteration: 9/20, moves: 45, ncost: 255939063769.12814
Run: 4, iteration: 10/20, moves: 39, ncost: 255843783691.12375
Run: 4, iteration: 11/20, moves: 35, ncost: 255792047572.66046
Run: 4, iteration: 12/20, moves: 27, ncost: 255754970004.72754
Run: 4, iteration: 13/20, moves: 34, ncost: 255709814479.95316
Run: 4, iteration: 14/20, moves: 14, ncost: 255701205250.8805
Run: 4, iteration: 15/20, moves: 7, ncost: 255699397602.56793
Run: 4, iteration: 16/20, moves: 2, ncost: 255699223839.03925
Run: 4, iteration: 17/20, moves: 2, ncost: 255699017354.36984
Run: 4, iteration: 18/20, moves: 2, ncost: 255698926481.13287
Run: 4, iteration: 19/20, moves: 3, ncost: 255698716105.73776
Run: 4, iteration: 20/20, moves: 0, ncost: 255698716105.73776
Init: initializing centroids
Init: initializing clusters
Init: initializing centroids
Init: initializing clusters
Init: initializing centroids
Init: initializing clusters
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 5, iteration: 1/20, moves: 391, ncost: 269560428492.02896
Run: 5, iteration: 2/20, moves: 266, ncost: 259808372458.51874
Run: 5, iteration: 3/20, moves: 200, ncost: 257518190889.69894
Run: 5, iteration: 4/20, moves: 142, ncost: 256711072394.02832
Run: 5, iteration: 5/20, moves: 92, ncost: 256413198677.2408
Run: 5, iteration: 6/20, moves: 58, ncost: 256211188795.21097
Run: 5, iteration: 7/20, moves: 33, ncost: 256124460537.68045
Run: 5, iteration: 8/20, moves: 50, ncost: 256036051526.73752
Run: 5, iteration: 9/20, moves: 45, ncost: 255939063769.12845
Run: 5, iteration: 10/20, moves: 39, ncost: 255843783691.12378
Run: 5, iteration: 11/20, moves: 35, ncost: 255792047572.66043
Run: 5, iteration: 12/20, moves: 27, ncost: 255754970004.72763
Run: 5, iteration: 13/20, moves: 34, ncost: 255709814479.953
Run: 5, iteration: 14/20, moves: 14, ncost: 255701205250.88074
Run: 5, iteration: 15/20, moves: 7, ncost: 255699397602.56763
Run: 5, iteration: 16/20, moves: 2, ncost: 255699223839.03918
Run: 5, iteration: 17/20, moves: 2, ncost: 255699017354.36993
Run: 5, iteration: 18/20, moves: 2, ncost: 255698926481.13278
Run: 5, iteration: 19/20, moves: 3, ncost: 255698716105.73764
Run: 5, iteration: 20/20, moves: 0, ncost: 255698716105.73764
Init: initializing centroids
Init: initializing clusters
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 6, iteration: 1/20, moves: 3685, ncost: 263751183547.74222
Run: 6, iteration: 2/20, moves: 590, ncost: 257639693100.52792
Run: 6, iteration: 3/20, moves: 180, ncost: 256763244852.94165
Run: 6, iteration: 4/20, moves: 94, ncost: 256451231642.09085
Run: 6, iteration: 5/20, moves: 69, ncost: 256228179953.5386
Run: 6, iteration: 6/20, moves: 39, ncost: 256124460537.6804
Run: 6, iteration: 7/20, moves: 50, ncost: 256036051526.7375
Run: 6, iteration: 8/20, moves: 45, ncost: 255939063769.12842
Run: 6, iteration: 9/20, moves: 39, ncost: 255843783691.12408
Run: 6, iteration: 10/20, moves: 35, ncost: 255792047572.66043
Run: 6, iteration: 11/20, moves: 27, ncost: 255754970004.7273
Run: 6, iteration: 12/20, moves: 34, ncost: 255709814479.9527
Run: 6, iteration: 13/20, moves: 14, ncost: 255701205250.88068
Run: 6, iteration: 14/20, moves: 7, ncost: 255699397602.56796
Run: 6, iteration: 15/20, moves: 2, ncost: 255699223839.03897
Run: 6, iteration: 16/20, moves: 2, ncost: 255699017354.36984
Run: 6, iteration: 17/20, moves: 2, ncost: 255698926481.1328
Run: 6, iteration: 18/20, moves: 3, ncost: 255698716105.73773
Run: 6, iteration: 19/20, moves: 0, ncost: 255698716105.73773
Init: initializing centroids
Init: initializing clusters
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 7, iteration: 1/20, moves: 850, ncost: 256929902713.14426
Run: 7, iteration: 2/20, moves: 146, ncost: 254661122532.982
Run: 7, iteration: 3/20, moves: 32, ncost: 254087579826.91
Run: 7, iteration: 4/20, moves: 19, ncost: 253971025447.93317
Run: 7, iteration: 5/20, moves: 9, ncost: 253960895337.96292
Run: 7, iteration: 6/20, moves: 11, ncost: 253923577189.4634
Run: 7, iteration: 7/20, moves: 3, ncost: 253922019246.0725
Run: 7, iteration: 8/20, moves: 0, ncost: 253922019246.0725
Init: initializing centroids
Init: initializing clusters
Init: initializing centroids
Init: initializing clusters
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 8, iteration: 1/20, moves: 761, ncost: 258485922303.82385
Run: 8, iteration: 2/20, moves: 223, ncost: 255971003683.42432
Run: 8, iteration: 3/20, moves: 43, ncost: 255780916964.5857
Run: 8, iteration: 4/20, moves: 30, ncost: 255733758962.00745
Run: 8, iteration: 5/20, moves: 24, ncost: 255705330314.85376
Run: 8, iteration: 6/20, moves: 13, ncost: 255700089506.1474
Run: 8, iteration: 7/20, moves: 5, ncost: 255699223839.03918
Run: 8, iteration: 8/20, moves: 2, ncost: 255699017354.36975
Run: 8, iteration: 9/20, moves: 2, ncost: 255698926481.1329
Run: 8, iteration: 10/20, moves: 3, ncost: 255698716105.7378
Run: 8, iteration: 11/20, moves: 0, ncost: 255698716105.7378
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 9, iteration: 1/20, moves: 741, ncost: 259351800639.69806
Run: 9, iteration: 2/20, moves: 101, ncost: 256909040587.04306
Run: 9, iteration: 3/20, moves: 66, ncost: 256526163878.11703
Run: 9, iteration: 4/20, moves: 61, ncost: 256327816960.44232
Run: 9, iteration: 5/20, moves: 42, ncost: 256185646857.40872
Run: 9, iteration: 6/20, moves: 29, ncost: 256107843496.47116
Run: 9, iteration: 7/20, moves: 48, ncost: 256023716306.94202
Run: 9, iteration: 8/20, moves: 48, ncost: 255922832934.74313
Run: 9, iteration: 9/20, moves: 32, ncost: 255840735738.4698
Run: 9, iteration: 10/20, moves: 33, ncost: 255792047572.66055
Run: 9, iteration: 11/20, moves: 27, ncost: 255754970004.72733
Run: 9, iteration: 12/20, moves: 34, ncost: 255709814479.95282
Run: 9, iteration: 13/20, moves: 14, ncost: 255701205250.8804
Run: 9, iteration: 14/20, moves: 7, ncost: 255699397602.56772
Run: 9, iteration: 15/20, moves: 2, ncost: 255699223839.0392
Run: 9, iteration: 16/20, moves: 2, ncost: 255699017354.37
Run: 9, iteration: 17/20, moves: 2, ncost: 255698926481.13278
Run: 9, iteration: 18/20, moves: 3, ncost: 255698716105.73776
Run: 9, iteration: 19/20, moves: 0, ncost: 255698716105.73776
Init: initializing centroids
Init: initializing clusters
Init: initializing centroids
Init: initializing clusters
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 10, iteration: 1/20, moves: 524, ncost: 268002187776.74048
Run: 10, iteration: 2/20, moves: 279, ncost: 259689284083.3353
Run: 10, iteration: 3/20, moves: 196, ncost: 257518190889.69907
Run: 10, iteration: 4/20, moves: 142, ncost: 256711072394.02838
Run: 10, iteration: 5/20, moves: 92, ncost: 256413198677.24078
Run: 10, iteration: 6/20, moves: 58, ncost: 256211188795.21097
Run: 10, iteration: 7/20, moves: 33, ncost: 256124460537.6805
Run: 10, iteration: 8/20, moves: 50, ncost: 256036051526.73746
Run: 10, iteration: 9/20, moves: 45, ncost: 255939063769.1284
Run: 10, iteration: 10/20, moves: 39, ncost: 255843783691.12396
Run: 10, iteration: 11/20, moves: 35, ncost: 255792047572.6603
Run: 10, iteration: 12/20, moves: 27, ncost: 255754970004.72748
Run: 10, iteration: 13/20, moves: 34, ncost: 255709814479.9532
Run: 10, iteration: 14/20, moves: 14, ncost: 255701205250.88052
Run: 10, iteration: 15/20, moves: 7, ncost: 255699397602.5677
Run: 10, iteration: 16/20, moves: 2, ncost: 255699223839.03915
Run: 10, iteration: 17/20, moves: 2, ncost: 255699017354.3698
Run: 10, iteration: 18/20, moves: 2, ncost: 255698926481.13272
Run: 10, iteration: 19/20, moves: 3, ncost: 255698716105.73758
Run: 10, iteration: 20/20, moves: 0, ncost: 255698716105.73758
Best run was number 7

In [10]:
print(kproto.cluster_centroids_)

[array([[31880.62665775, 31880.62665775, 31880.62665775, 31880.62665775],
       [ 5362.21300508,  5362.21300508,  5362.21300508,  5362.21300508],
       [14305.94684567, 14305.94684567, 14305.94684567, 14305.94684567]]), array([['California', 'Basic', 'Suburban'],
       ['California', 'Basic', 'Suburban'],
       ['California', 'Basic', 'Suburban']], dtype='<U10')]

In [0]:
cluster_dict=[]
for c in clusters:
    cluster_dict.append(c)

In [12]:
cluster_dict

[1,
 2,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 0,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 0,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 0,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 0,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 0,
 2,
 1,
 0,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 0,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 2,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 0,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 0,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 0,
 2,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 0,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 0,
 1,
 2,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 2,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 2,
 2,
 2,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 0,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 0,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 2,
 1,
 0,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 0,
 1,
 0,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 0,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 2,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 0,
 1,
 2,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 2,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 0,
 2,
 2,
 1,
 1,
 1,
 1,
 ...]

In [0]:
marketing_df['cluster']=cluster_dict

In [14]:
marketing_df

           State           CLV  ... Months_Since_Policy_Inception  cluster
0     Washington   2763.519279  ...                             5        1
1         Nevada  12887.431650  ...                            38        2
2     Washington   2813.692575  ...                            44        1
3         Oregon   8256.297800  ...                            94        1
4         Oregon   5380.898636  ...                            13        1
...          ...           ...  ...                           ...      ...
6812  California   5032.165498  ...                            48        1
6813  California   4100.398533  ...                            58        1
6814  California  23405.987980  ...                            89        0
6815  California   3096.511217  ...                            28        1
6816  California   7524.442436  ...                             3        1

[6817 rows x 8 columns]

In [15]:
marketing_df[marketing_df['cluster']== 0].head(10)

          State          CLV  ... Months_Since_Policy_Inception  cluster
5        Oregon  24127.50402  ...                             3        0
17      Arizona  24127.50402  ...                             3        0
37       Oregon  36707.42639  ...                            28        0
38   California  33473.34946  ...                            95        0
48   California  24261.01777  ...                            86        0
61   California  58166.55351  ...                            30        0
90   Washington  24084.53520  ...                            54        0
99       Oregon  31221.74810  ...                            27        0
178     Arizona  32269.85139  ...                            70        0
204     Arizona  29328.04185  ...                             7        0

[10 rows x 8 columns]

In [16]:
marketing_df[marketing_df['cluster']== 1].head(10)

         State          CLV  ... Months_Since_Policy_Inception  cluster
0   Washington  2763.519279  ...                             5        1
2   Washington  2813.692575  ...                            44        1
3       Oregon  8256.297800  ...                            94        1
4       Oregon  5380.898636  ...                            13        1
6       Oregon  7388.178085  ...                             7        1
7   California  8798.797003  ...                            82        1
8      Arizona  8819.018934  ...                            25        1
9   California  5384.431665  ...                            10        1
10      Oregon  7463.139377  ...                            50        1
11      Nevada  2566.867823  ...                             7        1

[10 rows x 8 columns]

In [17]:
marketing_df[marketing_df['cluster']== 2].head(10)

         State          CLV  ... Months_Since_Policy_Inception  cluster
1       Nevada  12887.43165  ...                            38        2
21     Arizona  12902.56014  ...                            54        2
24      Nevada  18975.45611  ...                            14        2
28  California  13891.73567  ...                            62        2
33     Arizona  12231.87968  ...                            16        2
35      Oregon  12819.10289  ...                             4        2
51     Arizona  11638.66926  ...                            65        2
52  California  11727.77648  ...                             0        2
53      Oregon  22643.83478  ...                            12        2
60  Washington  11318.08982  ...                            83        2

[10 rows x 8 columns]